#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
#bspc monitor MON2 V VI VII ...

bspc config border_width         2
bspc config window_gap           5
#bspc config border_radius        20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#EXAMPLES

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

nitrogen --restore
$HOME/.config/polybar/launch.sh 
bspc config top_padding          35
#bspc config active_border_color "#0C1115"
#bspc config normal_border_color "#0C1115"
# bspc config focused_border_color "#ffffff"
bspc config focused_border_color "#ffff00"
bspc config normal_border_color "#ffffff"

wmname LG3D
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh

