#! /usr/bin/bash
cd
cd dotfiles
cp .bashrc .gtkrc-2.0.mine .scripts .zshrc .config .p10k.zsh .xbindkeysrc .bash_profile Pictures .xinitrc ~/ -r
cd
cd .config
cp accels.scm xfce4/terminal/accels.scm
cp gruvbox ~/.local/share/xfce4/terminal/colorschemes/ -r
