#! /usr/bin/bash

for i in *.md ; do echo "$i" && pandoc -s $i -o ~/wikihtml/$i.html && perl -pi -e 's/href="(?!#)(.*)"/href="$1\.md\.html"/g' ~/wikihtml/$i.html;done

# old way

# for i in *.md ; do echo "$i" && pandoc -s $i -o ~/wikihtml/$i.html && sed -i 's/\(href=".*\)\("\)/\1\.md\.html\2/g' ~/wikihtml/$i.html ; done
